./intersect_checks.py pha_subaa
./intersect_checks.py pha_subab
./intersect_checks.py pha_subac
./intersect_checks.py pha_subad
./intersect_checks.py pha_subae
./intersect_checks.py pha_subaf
./intersect_checks.py pha_subag
./intersect_checks.py pha_subah
./intersect_checks.py pha_subai
./intersect_checks.py pha_subaj
./intersect_checks.py pha_subak
./intersect_checks.py pha_subal
./intersect_checks.py pha_subam
./intersect_checks.py pha_suban
./intersect_checks.py pha_subao
./intersect_checks.py pha_subap
./intersect_checks.py pha_subaq
./intersect_checks.py pha_subar
./intersect_checks.py pha_subas
./intersect_checks.py pha_subat
